/** @type {import("tailwindcss").Config} */
module.exports = {
  content: ["./web/templates/**/*.html"],
  safelist: [
    "cais-password-wrap",
    "cais-password-toggle",
    "cais-chat-scroll-down",
    "cais-thinking",
    "cais-thinking-dots",
    "cais-select-search",
    "cais-select-search-native",
    "cais-select-search-trigger",
    "cais-select-search-panel",
    "cais-select-search-input",
    "cais-select-search-list",
    "cais-select-search-option",
    "cais-select-search-label",
    "cais-select-search-chevron",
    "is-selected",
    "is-highlighted",
    "is-hidden",
  ],
  theme: {
    extend: {
      colors: {
        ink: "#081014",
        foam: "#f3ead8",
        copper: "#c9893a",
        tide: "#14343c",
        surface: "#faf8ff",
        background: "#faf8ff",
        'on-surface': "#131b2e",
        'on-surface-variant': "#434655",
        outline: "#737686",
        primary: "#004ac6",
        'primary-container': "#2563eb",
        'on-primary': "#ffffff",
        secondary: "#006c49",
        'secondary-container': "#6cf8bb",
        'on-secondary-container': "#00714d",
        tertiary: "#784b00",
        'tertiary-container': "#996100",
        'tertiary-fixed': "#ffddb8",
        'tertiary-fixed-dim': "#ffb95f",
        'surface-container-lowest': "#ffffff",
        'surface-container-low': "#f2f3ff",
        'surface-container': "#eaedff",
        'surface-container-high': "#e2e7ff",
        'surface-container-highest': "#dae2fd",
        'primary-fixed': "#dbe1ff",
        'primary-fixed-dim': "#b4c5ff",
        'secondary-fixed': "#6ffbbe",
        error: "#ba1a1a",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Avenir Next", "Segoe UI", "system-ui", "sans-serif"],
        serif: ["Iowan Old Style", "Palatino Linotype", "Palatino", "Georgia", "serif"],
        display: ["Iowan Old Style", "Palatino Linotype", "Palatino", "Georgia", "serif"],
        mono: ["IBM Plex Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        'display-time': ["JetBrains Mono", "ui-monospace", "monospace"],
        'headline-xl': ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        'metric-tabular': ["JetBrains Mono", "ui-monospace", "monospace"],
        'body-md': ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      boxShadow: {
        "2xs": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      spacing: {
        gutter: "1.25rem",
        "gutter-desktop": "1.75rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontSize: {
        "display-time": ["56px", { lineHeight: "64px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "metric-tabular": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
